#!/usr/bin/env python3
"""
Genera js/notas.js a partir de la estructura de carpetas en notas/

Escanea el directorio notas/:
  - Cada subcarpeta se convierte en una categoría (diario, thincc, etc.)
  - Los archivos .md sueltos en la raíz van a la categoría 'sueltas'

Para cada nota extrae:
  - titulo:  primer encabezado # del .md, o nombre del archivo si no hay
  - preview: primeras ~150 chars de texto (sin encabezados)
  - fecha:   fecha de creación del archivo (st_birthtime, macOS)
  - hora:    hora de creación
  - dia:     día de la semana en español
  - media:   'img' si contiene imágenes, 'video' si contiene audio/vídeo

Uso: python3 generar_notas_js.py
"""

import os
import json
import re
from datetime import datetime

NOTAS_DIR = os.path.join(os.path.dirname(__file__), 'notas')
OUTPUT = os.path.join(os.path.dirname(__file__), 'js', 'notas.js')

# carpetas a ignorar dentro de notas/
SKIP = {'.DS_Store', 'attachments', 'images'}


def extraer_info(filepath):
    """Lee un .md y extrae metadatos para el frontend."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            contenido = f.read()
    except Exception:
        return None

    lines = contenido.strip().split('\n')
    titulo = ''
    preview_lines = []

    # primer # = título, las siguientes líneas no vacías = preview
    for line in lines:
        stripped = line.strip()
        if not titulo and stripped.startswith('#'):
            titulo = re.sub(r'^#+\s*', '', stripped)
        elif stripped and len(preview_lines) < 3:
            preview_lines.append(stripped)

    if not titulo:
        titulo = os.path.splitext(os.path.basename(filepath))[0]

    preview = ' '.join(preview_lines)[:150]

    # detectar tipos de media (pueden coexistir)
    has_img = bool(re.search(r'\.(png|jpg|jpeg|gif|svg|webp)', contenido, re.I))
    has_video = bool(re.search(r'\.(mp4|mov|webm)', contenido, re.I))
    has_audio = bool(re.search(r'\.(mp3|ogg|m4a|wav|flac)', contenido, re.I))

    # detectar si contiene links (markdown [text](url) o URLs sueltas)
    has_links = bool(re.search(r'\[.+?\]\(https?://', contenido)) or \
                bool(re.search(r'(?<!\()https?://\S+', contenido))

    # fecha de creación (st_birthtime solo en macOS)
    stat = os.stat(filepath)
    dt = datetime.fromtimestamp(stat.st_birthtime)

    dias_es = ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo']

    return {
        'archivo': os.path.relpath(filepath, NOTAS_DIR),
        'titulo': titulo,
        'fecha': dt.strftime('%d/%m/%y'),    # 02/03/23
        'hora': dt.strftime('%H:%M'),        # 14:32
        'dia': dias_es[dt.weekday()],        # miércoles
        'preview': preview,
        'img': has_img,
        'video': has_video,
        'audio': has_audio,
        'links': has_links,
        '_sort': stat.st_birthtime,          # campo interno, se borra antes de exportar
    }


def main():
    categorias = {}

    for entry in sorted(os.listdir(NOTAS_DIR)):
        full = os.path.join(NOTAS_DIR, entry)

        if entry in SKIP or entry.startswith('.'):
            continue

        if os.path.isdir(full):
            # subcarpeta = categoría
            notas = []
            for root, dirs, files in os.walk(full):
                dirs[:] = [d for d in dirs if d not in SKIP]
                for f in sorted(files):
                    if f.endswith('.md') and not f.startswith('.'):
                        info = extraer_info(os.path.join(root, f))
                        if info:
                            notas.append(info)
            notas.sort(key=lambda n: n['_sort'], reverse=True)
            if notas:
                categorias[entry] = notas

        elif entry.endswith('.md'):
            # archivo suelto en raíz → categoría 'sueltas'
            if 'sueltas' not in categorias:
                categorias['sueltas'] = []
            info = extraer_info(full)
            if info:
                categorias['sueltas'].append(info)

    # ordenar todas las categorías y limpiar campo interno
    for cat in categorias:
        categorias[cat].sort(key=lambda n: n['_sort'], reverse=True)
        for nota in categorias[cat]:
            del nota['_sort']

    # exportar como módulo ES6
    js = '// Auto-generated by generar_notas_js.py\n'
    js += '// No editar manualmente\n\n'
    js += 'export const categorias = '
    js += json.dumps(categorias, ensure_ascii=False, indent=2)
    js += ';\n'

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(js)

    total = sum(len(v) for v in categorias.values())
    print(f'Generado {OUTPUT}')
    print(f'{len(categorias)} categorías, {total} notas total')
    for k, v in categorias.items():
        print(f'  {k}: {len(v)}')


if __name__ == '__main__':
    main()
