#!/usr/bin/env python3
"""
Genera js/notas.js a partir de la estructura de carpetas en notas/
Cada carpeta = categoría, archivos .md sueltos = 'sueltas'
"""

import os
import json
import re

NOTAS_DIR = os.path.join(os.path.dirname(__file__), 'notas')
OUTPUT = os.path.join(os.path.dirname(__file__), 'js', 'notas.js')

SKIP = {'.DS_Store', 'attachments', 'images'}


def extraer_info(filepath):
    """Lee un .md y extrae título y preview."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            contenido = f.read()
    except:
        return None

    lines = contenido.strip().split('\n')
    titulo = ''
    preview_lines = []

    for line in lines:
        stripped = line.strip()
        if not titulo and stripped.startswith('#'):
            titulo = re.sub(r'^#+\s*', '', stripped)
        elif stripped and len(preview_lines) < 3:
            preview_lines.append(stripped)

    if not titulo:
        # usar nombre de archivo como título
        titulo = os.path.splitext(os.path.basename(filepath))[0]

    preview = ' '.join(preview_lines)[:150]

    # detectar media
    media = None
    if re.search(r'\.(png|jpg|jpeg|gif|svg|webp)', contenido, re.I):
        media = 'img'
    if re.search(r'\.(mp4|mov|webm|mp3|ogg|m4a)', contenido, re.I):
        media = 'video'

    # fecha de creación (birthtime en macOS)
    stat = os.stat(filepath)
    birthtime = stat.st_birthtime
    from datetime import datetime
    fecha = datetime.fromtimestamp(birthtime).strftime('%d %b %Y')

    rel_path = os.path.relpath(filepath, NOTAS_DIR)

    return {
        'archivo': rel_path,
        'titulo': titulo,
        'fecha': fecha,
        'preview': preview,
        'media': media,
        '_sort': birthtime,
    }


def main():
    categorias = {}

    for entry in sorted(os.listdir(NOTAS_DIR)):
        full = os.path.join(NOTAS_DIR, entry)

        if entry in SKIP or entry.startswith('.'):
            continue

        if os.path.isdir(full):
            # carpeta = categoría
            cat_name = entry
            notas = []
            for root, dirs, files in os.walk(full):
                # skip attachment/image subdirs
                dirs[:] = [d for d in dirs if d not in SKIP]
                for f in sorted(files):
                    if f.endswith('.md') and not f.startswith('.'):
                        info = extraer_info(os.path.join(root, f))
                        if info:
                            notas.append(info)
            # ordenar por fecha creación: más reciente primero
            notas.sort(key=lambda n: n['_sort'], reverse=True)
            if notas:
                categorias[cat_name] = notas

        elif entry.endswith('.md'):
            # archivo suelto → categoría 'sueltas'
            if 'sueltas' not in categorias:
                categorias['sueltas'] = []
            info = extraer_info(full)
            if info:
                categorias['sueltas'].append(info)

    # ordenar sueltas también
    for cat in categorias:
        categorias[cat].sort(key=lambda n: n['_sort'], reverse=True)
        # quitar campo interno _sort
        for nota in categorias[cat]:
            del nota['_sort']

    # generar JS
    js = '// Auto-generated by generar_notas_js.py\n'
    js += '// No editar manualmente\n\n'
    js += 'export const categorias = '
    js += json.dumps(categorias, ensure_ascii=False, indent=2)
    js += ';\n'

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(js)

    total = sum(len(v) for v in categorias.values())
    print(f'Generado {OUTPUT}')
    print(f'{len(categorias)} categorías, {total} notas total')
    for k, v in categorias.items():
        print(f'  {k}: {len(v)}')


if __name__ == '__main__':
    main()
